#!/usr/bin/env bash
alias qnb="cd ~/devel/qnx/qnx8-bsp"
alias qne="cd ~/devel/qnx/qnx8-bsp/src/hardware/support/ele"
alias qns="cd /home/polachz/devel/qnx/qnx8-ele/qnx-imx-secure-enclave"

alias qc="imxcon"

export QNX_SDP_PATH="${HOME}/qnx800"
