#!/usr/bin/env bash
# Git shortcuts.

alias g="git"
alias gcm='git commit -m'
alias gst='git status'
# Add modified and deleted files to stash
alias gam='git add -u'
# Add files to stash
alias ga='git add'
